apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-generator
spec:
  selector: 
    matchLabels:
      app: workload-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: workload-generator
    spec: 
      containers:
      - name: workload-generator
        image: dhartl231198/k8s-workload
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
---
kind: Service
apiVersion: v1
metadata:
 name: workload-generator
spec:
 selector:
   app: workload-generator
 ports:
 - protocol: TCP
   port: 5200
   nodePort: 30088
 type: NodePort
